### ISSUE TITLE
TV Logos not showing from m3u

### ISSUE THREAD

**Issue by cjhines7** [Mariusz89B/script.mtvguide#13]
I'm have created a M3U and XML file from m3u4u.com and the logos do not show in the addon. I checked and the tvg-logos are in the m3u, not the xml. Do logos only load from the xml and not the m3u? Addon version 9.8.5, Kodi 19.3

**Comment by Mariusz89B** [comment]
Hi, yes channel logos are only loaded from the EPG (XMLTV File). Could you provide a string with the channel logos in a M3U, let me check if it's possible to import them as well.

Otherwise you could add a folder with your channel logos, this setting is available in 9.8.6:
https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.8.6

Wiki:
https://github.com/Mariusz89B/script.mtvguide/wiki/Wiki#search-for-channel-logos-in-xmltv_logo_folder
